title: Minesweeper 4D
description: >-
  Generate a Minesweeper 4D field and send it to your Minecraft client.

domain: vonas.github.io
url: https://vonas.github.io
baseurl: /minesweeper4d

assets: assets
theme: null

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
