title: Minesweeper 4D
description: >-
  Generate a Minesweeper 4D field and send it to your Minecraft client.

domain: vonas.github.io
url: https://vonas.github.io
baseurl: /minesweeper4d

assets: assets
theme: null

plugins:
  - jekyll-minifier

jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:
    harmony: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

blocks:
  classes:
    - bzp # full blocks
    - cet # redstone block
    - ccl # glass
    - cgk # stained glass
  allowed:
    colors:
      - glass
      - smooth_stone
      - green_wool
      - yellow_wool
      - orange_wool
      - red_wool
      - purple_wool
      - light_blue_wool
      - blue_wool
      - black_wool
      - brown_wool
      - cyan_wool
      - lime_wool
      - pink_wool
      - gray_wool
      - light_gray_wool
      - white_wool
  defaults:
    cover: sandstone
    mine: glowstone
    colors:
      - glass
      - lime_wool
      - yellow_wool
      - orange_wool
      - red_wool
      - purple_wool
      - light_blue_wool
      - blue_wool
      - black_wool
      - brown_wool
      - cyan_wool
      - green_wool
      - pink_wool
      - gray_wool
      - light_gray_wool
      - white_wool
